### ISSUE TITLE
Error: List index out of range

### ISSUE THREAD

**Issue by jviseur** [cocktailpeanut/whisper-webui.pinokio#4]
T2T Translation process gives me an error as soon as the translation starts.  It matters not what model I use or what target language I use.
It was working fine last week when I was using it on Pinokio 1.3.4

I also found an issue with Youtube option when creating an SRT, WEBVTT or TXT file abot 3 seconds in gives Error: HTTP Error 400: Bad Request.

Also a month ago when processing T2T translations it was using my AMD GPU which it no longer does a few days ago before I upgraded Whisper-webui

I found this in terminal session
Traceback (most recent call last):
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\gradio\utils.py", line 704, in wrapper
    response = f(*args, **kwargs)
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\modules\faster_whisper_inference.py", line 291, in transcribe_mic
    self.remove_input_files([micaudio])
  File "C:\pinokio\api\whisper-webui.pinokio.git\app\modules\base_interface.py", line 19, in remove_input_files
    if not os.path.exists(file_path):
  File "C:\pinokio\bin\miniconda\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
C:\pinokio\api\whisper-webui.pinokio.git\app\venv\lib\site-packages\gradio\processing_utils.py:188: UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))

**Comment by jviseur** [comment]
Issue resolved
